spring:
  application:
    name: edo-scheduler

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

integration:
  url:
    employee: https://5b1fc2ba-e02c-4017-9744-6463c84600d3.mock.pstmn.io/employees
cron-expression:
  employee:'0 * * * *'


