variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=50"

stages:
  - build_artifacts
#  - build_image
#  - deploy

build_artifacts:
  stage: build_artifacts
  image: maven:3.6.3-openjdk-17-slim
  cache:
    paths:
      - ./.m2/repository
    key: project-cache
  tags:
    - runner
  script:
    - mvn clean $MAVEN_OPTS compile -DskipTests
#build-image:
