spring:
  application:
    name: edo-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info