spring:
  application:
    name: edo-integration
  mail:
    protocol: smtps
    host: smtp.yandex.ru
    port: 465
    username: noreply.edo.test@yandex.ru
    password: nsouxadxzcnnivem
    test-connection: true # Проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info