spring:
  application:
    name: edo-integration
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.ros.edo@gmail.com
    password: ezbghhqgfhduhigl
    test-connection: true # Проверка подключения при старте приложения
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true