spring:
  flyway:
    enabled: true
    user: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/edo_db
    default-schema: edo
    locations: db/migration
  jpa:
    properties:
      hibernate:
        default_schema: edo
  application:
    name: edo-repository
server:
  enableSelfPreservation: fasle
  port: 8889
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
