spring:
  application:
    name: edo-file-storage
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
minio:
  endpoint: http://127.0.0.1:9000
  username: admin
  password: password
  sourcefolder: C:\Users\akhme\minio\fileHolder\
  targetfolder: C:\Users\akhme\minio\targetFolder\
